spring:
  data:
    mongodb:
      uri: mongodb+srv://mergimjanuzi:B6Dtq6NS50lGGoxr@mergimcluster.ffqai.mongodb.net/

jwt:
  secret: hfaiehfisehfosndfejndfeswljrfeowfnjehwbewios4ngvhtrwglp4rkledf
  expirationMs: 360000000.